---
version: '3.4'

x-base: &base
  volumes:
    - "$HOME/.kube:/root/.kube"
    - "~/.aws:/root/.aws"
    - ".:/app"
  working_dir: /app
  environment:
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION-ap-southeast-2}
    - AWS_PROFILE=${AWS_PROFILE-default}

services:

  stackup:
    <<: *base
    image: realestate/stackup

  awscli:
    <<: *base
    image: myobplatform/aws-jq:0.1.0
