---
version: '3.4'

x-base: &base
  build: .
  volumes:
    - "$HOME/.kube:/root/.kube"
    - "~/.aws:/root/.aws"
    - ".:/app"
  working_dir: /app
  environment:
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION-ap-southeast-2}
    - AWS_PROFILE=${AWS_PROFILE-default}

services:

  sh:
    <<: *base

  stackup:
    <<: *base
    entrypoint: stackup

  awscli:
    <<: *base
    entrypoint: aws
